services:
  dbmysql:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: prueba
      MYSQL_USER: test
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local

